### PR TITLE
fix(server): don't show suggestions in meta values

### LINKED ISSUE #14: Enable auto-complete only in specific attributes
Maybe only for `formule`, `valeur`, `par défaut`

Related to #10

### PR DESCRIPTION
**Pull request by EmileRolley**
Fixes #14

### CODE REVIEW

File: server/src/completion.ts [hunk 1]
```diff
@@ -10,21 +10,41 @@ import { RuleNode } from "publicodes";
...
+    // having a single source of truth for the tree (even though it's can
+    // force to manage async operations with the cost it implies).
+    const fileContent = ctx.documents.get(textDocument.uri)?.getText()!;
+    const tsTree = getTSTree(fileContent);
+
+    const nodeAtCursorPosition = tsTree?.rootNode.descendantForPosition({
+      row: position.line,
+      // We need to be sure to be in the current node, even if the cursor is
+      // at the end of the line.
+      column: position.character - 1,
```
Comment (Clemog) [inline server/src/completion.ts:38]: Ah yes bien vu

**Review by Clemog — APPROVED** [review]
